stages:
  - package

build_image:
  stage: package
  variables:
    TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  tags:
    - docker-image-build
  script:
  - echo building image
  
build_sam:
  stage: package
  script:
    - docker build -t gitlab-registry.cern.ch/meehan/faser-docker-daq:latest .
    - docker push gitlab-registry.cern.ch/meehan/faser-docker-daq:latest
