stages:
  - package

#build_image:
#  stage: package
#  variables:
#    TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
#  tags:
#    - docker-image-build
#  script:
#  - echo building image
  
build_daq:
  image: gitlab-registry.cern.ch/ci-tools/docker-image-builder:latest
  stage: package
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:latest

build_daq_tag:
  image: gitlab-registry.cern.ch/ci-tools/docker-image-builder:latest
  stage: package
  only: [tags]
  script:
    - echo ${CI_COMMIT_TAG}
#    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} .
#    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}

build_docker:
  stage: package
  tags: 
  - docker-privileged
  # Use specific version of the official docker client image (as well as the docker-in-docker image) as recommended by
  # https://about.gitlab.com/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  image: docker:19.03.1
  services:
  # To obtain a Docker daemon, request a Docker-in-Docker service
  - docker:19.03.1-dind
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
