stages:
  - package

build_daq:
  stage: package
  tags:
    - docker
  script:
    - ls
    - cd docker-faser-daq
    - docker build -t gitlab-registry.cern.ch/meehan/docker-faser-daq:latest .
    - docker push gitlab-registry.cern.ch/meehan/docker-faser-daq:latest
    
#build_offline:
#  stage: package
#  tags:
#    - docker
#  script:
#    - cd docker-faser-offline
#    - docker build -t gitlab-registry.cern.ch/meehan/docker-faser-offline:latest .
#    - docker push gitlab-registry.cern.ch/meehan/docker-faser-offline:latest
  
  
