# guidance taken from the IT folks
#
# https://gitlab.cern.ch/ci-tools/docker-image-builder#run-a-docker-build-job
# https://gitlab.cern.ch/gitlabci-examples/build_docker_image/blob/master/.gitlab-ci.yml
#
# FixMe : In the future, we should be using kaniko, but Sam Meehan doesn't know what that is

stages:
  - package

build_daq:
  stage: package
  tags: 
  - docker-privileged
  image: docker:19.03.1
  services:
  - docker:19.03.1-dind
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/daq:$CI_COMMIT_REF_SLUG ./faser-daq
    - docker push $CI_REGISTRY_IMAGE/daq:$CI_COMMIT_REF_SLUG
    
    
build_offline:
  stage: package
  tags: 
  - docker-privileged
  image: docker:19.03.1
  services:
  - docker:19.03.1-dind
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/offline:$CI_COMMIT_REF_SLUG ./faser-offline
    - docker push $CI_REGISTRY_IMAGE/offline:$CI_COMMIT_REF_SLUG

